import fs from "node:fs/promises";
import { dependencyHelp } from "./dependencies.js";
import { UnlocalhostError } from "./errors.js";
import { projectEndpoints, type ResolvedEndpoint } from "./endpoints.js";
import { exists, writeAtomic } from "./files.js";
import { pathsFor } from "./paths.js";
import { commandExists, runCommand } from "./process.js";
import { listProjects } from "./registry.js";
import { endpointLocalUrl, endpointPublicUrl } from "./urls.js";
import type { GlobalConfig, ProjectConfig } from "./types.js";

function routeMarker(project: ProjectConfig, endpoint: ResolvedEndpoint): string {
  return endpoint.primary
    ? `unlocalhost-project:${project.id}`
    : `unlocalhost-project:${project.id}:endpoint:${endpoint.id}`;
}

function hostnameFromUrl(url: string): string {
  return new URL(url).hostname;
}

function routeBlock(
  addresses: string[],
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
  tlsInternal: boolean,
  forwardedProto?: "https",
): string {
  const proxy = forwardedProto
    ? [
        `\treverse_proxy ${endpoint.upstream.host}:${endpoint.upstream.port} {`,
        `\t\theader_up X-Forwarded-Proto ${forwardedProto}`,
        "\t\theader_up X-Forwarded-Port 443",
        "\t}",
      ]
    : [`\treverse_proxy ${endpoint.upstream.host}:${endpoint.upstream.port}`];
  const lines = [
    `# ${routeMarker(project, endpoint)}`,
    `${addresses.join(", ")} {`,
    ...(tlsInternal ? ["\ttls internal"] : []),
    ...proxy,
    "}",
  ];
  return lines.join("\n");
}

export function generateCaddyfile(config: GlobalConfig, projects: ProjectConfig[]): string {
  const enabled = projects.filter((project) => project.enabled);
  const blocks: string[] = [
    [
      "# Generated by unlocalhost. Project TOML files are the source of truth.",
      "{",
      "\tadmin 127.0.0.1:2019",
      `\thttp_port ${config.caddy_http_port}`,
      `\thttps_port ${config.caddy_https_port}`,
      "\tskip_install_trust",
      "}",
    ].join("\n"),
  ];
  for (const project of enabled) {
    for (const endpoint of projectEndpoints(project)) {
      const local = hostnameFromUrl(endpointLocalUrl(endpoint, config));
      const publicUrl = endpointPublicUrl(endpoint, config);
      blocks.push(
        routeBlock(
          [`http://${local}:${config.caddy_http_port}`],
          project,
          endpoint,
          false,
        ),
        routeBlock(
          [`https://${local}:${config.caddy_https_port}`],
          project,
          endpoint,
          true,
        ),
      );
      if (publicUrl) {
        blocks.push(
          routeBlock(
            [`http://${hostnameFromUrl(publicUrl)}:${config.caddy_http_port}`],
            project,
            endpoint,
            false,
            "https",
          ),
        );
      }
    }
  }
  if (enabled.length === 0) {
    blocks.push([
      `http://:${config.caddy_http_port}, https://:${config.caddy_https_port} {`,
      "\trespond \"No unlocalhost projects are registered\" 404",
      "}",
    ].join("\n"));
  }
  return `${blocks.join("\n\n")}\n`;
}

export async function rebuildCaddyfile(
  home: string,
  config: GlobalConfig,
): Promise<{ file: string; projectCount: number }> {
  const projects = await listProjects(home);
  const file = pathsFor(home).caddyfile;
  await writeAtomic(file, generateCaddyfile(config, projects));
  return { file, projectCount: projects.filter((project) => project.enabled).length };
}

export async function validateCaddyfile(home: string): Promise<void> {
  if (!commandExists("caddy")) {
    throw new UnlocalhostError(dependencyHelp("caddy"));
  }
  const result = await runCommand("caddy", [
    "validate",
    "--config",
    pathsFor(home).caddyfile,
    "--adapter",
    "caddyfile",
  ]);
  if (result.code !== 0) {
    throw new UnlocalhostError(`Caddy validation failed: ${result.stderr || result.stdout}`);
  }
}

export async function reloadCaddy(home: string): Promise<void> {
  await validateCaddyfile(home);
  const result = await runCommand("caddy", [
    "reload",
    "--config",
    pathsFor(home).caddyfile,
    "--adapter",
    "caddyfile",
  ]);
  if (result.code !== 0) {
    throw new UnlocalhostError(`Caddy reload failed: ${result.stderr || result.stdout}`);
  }
}

export async function maybeReloadCaddy(home: string): Promise<boolean> {
  if (!commandExists("caddy") || !(await exists(pathsFor(home).caddyfile))) return false;
  await validateCaddyfile(home);
  const result = await runCommand("caddy", [
    "reload",
    "--config",
    pathsFor(home).caddyfile,
    "--adapter",
    "caddyfile",
  ]);
  return result.code === 0;
}

export async function routeExists(home: string, id: string): Promise<boolean> {
  return await endpointRouteExists(home, id, "web");
}

export async function endpointRouteExists(
  home: string,
  projectId: string,
  endpointId: string,
): Promise<boolean> {
  const file = pathsFor(home).caddyfile;
  if (!(await exists(file))) return false;
  const marker =
    endpointId === "web"
      ? `# unlocalhost-project:${projectId}\n`
      : `# unlocalhost-project:${projectId}:endpoint:${endpointId}\n`;
  return (await fs.readFile(file, "utf8")).includes(marker);
}
