import fs from "node:fs/promises";
import path from "node:path";
import { loadGlobalConfig, parseProject, serializeProject } from "./config.js";
import { UnlocalhostError } from "./errors.js";
import { getEndpoint, projectEndpoints } from "./endpoints.js";
import { assertInside, exists, writeAtomic } from "./files.js";
import { pathsFor } from "./paths.js";
import { allocatePort } from "./ports.js";
import { stopEndpointRunner, stopProjectRunners } from "./runner.js";
import type { DevServerKind, EndpointConfig, ProjectConfig } from "./types.js";

const SLUG_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

export function validateSlug(slug: string): string {
  const normalized = slug.toLowerCase();
  if (!SLUG_PATTERN.test(normalized)) {
    throw new UnlocalhostError(
      `Invalid slug "${slug}": use 1-63 lowercase letters, digits, or internal hyphens`,
    );
  }
  return normalized;
}

function projectFile(home: string, id: string): string {
  const safeId = validateSlug(id);
  return path.join(pathsFor(home).projects, `${safeId}.toml`);
}

async function withRegistryLock<T>(home: string, action: () => Promise<T>): Promise<T> {
  const lockFile = path.join(home, ".registry.lock");
  for (let attempt = 0; attempt < 50; attempt += 1) {
    let handle: fs.FileHandle | null = null;
    try {
      handle = await fs.open(lockFile, "wx", 0o600);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
      const stat = await fs.stat(lockFile).catch(() => null);
      if (stat && Date.now() - stat.mtimeMs > 30_000) {
        await fs.rm(lockFile, { force: true });
        continue;
      }
      await new Promise((resolve) => setTimeout(resolve, 50));
      continue;
    }
    await handle.writeFile(`${process.pid}\n`);
    try {
      return await action();
    } finally {
      await handle.close();
      await fs.rm(lockFile, { force: true });
    }
  }
  throw new UnlocalhostError("Another unlocalhost registry operation is still running; retry shortly");
}

export async function listProjects(home: string): Promise<ProjectConfig[]> {
  await loadGlobalConfig(home);
  const directory = pathsFor(home).projects;
  const entries = await fs.readdir(directory, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".toml"))
    .map((entry) => entry.name)
    .sort();
  return await Promise.all(
    files.map(async (name) =>
      parseProject(await fs.readFile(path.join(directory, name), "utf8"), name),
    ),
  );
}

export async function getProject(home: string, id: string): Promise<ProjectConfig> {
  const file = projectFile(home, id);
  if (!(await exists(file))) {
    throw new UnlocalhostError(`Project "${id}" is not registered`);
  }
  return parseProject(await fs.readFile(file, "utf8"), path.basename(file));
}

export interface AddProjectOptions {
  path: string;
  slug: string;
  port?: number;
  host?: string;
  compose?: string;
  composePortServices?: string[];
  service?: string;
  containerPort?: number;
  name?: string;
  run?: string[];
  public?: boolean;
  dev?: boolean;
  devServer?: DevServerKind;
}

export interface AddEndpointOptions {
  id: string;
  slug?: string;
  port?: number;
  host?: string;
  service?: string;
  containerPort?: number;
  run?: string[];
  dev?: boolean;
  devServer?: DevServerKind;
}

function validateComposeService(service: string): string {
  if (!/^[a-zA-Z0-9_.-]+$/.test(service)) {
    throw new UnlocalhostError(`Invalid Compose service "${service}"`);
  }
  return service;
}

function composeOverrideYaml(project: ProjectConfig): string {
  const mappings = projectEndpoints(project)
    .filter(
      (endpoint) =>
        endpoint.compose_service !== undefined &&
        endpoint.container_port !== undefined,
    )
    .map((endpoint) => ({
      service: validateComposeService(endpoint.compose_service!),
      hostPort: endpoint.upstream.port,
      containerPort: endpoint.container_port!,
    }));
  const grouped = new Map<string, Array<{ hostPort: number; containerPort: number }>>();
  for (const mapping of mappings) {
    const ports = grouped.get(mapping.service) ?? [];
    ports.push(mapping);
    grouped.set(mapping.service, ports);
  }
  const lines = [
    "# Generated by unlocalhost outside the project repository.",
    "services:",
  ];
  const services = new Set([
    ...(project.compose_port_services ?? []).map(validateComposeService),
    ...grouped.keys(),
  ]);
  for (const service of services) {
    const ports = grouped.get(service) ?? [];
    lines.push(`  ${service}:`);
    if (ports.length === 0) {
      lines.push("    ports: !override []");
    } else {
      lines.push("    ports: !override");
      for (const mapping of ports) {
        lines.push(
          `      - "127.0.0.1:${mapping.hostPort}:${mapping.containerPort}"`,
        );
      }
    }
  }
  lines.push("");
  return lines.join("\n");
}

async function updateComposeOverride(home: string, project: ProjectConfig): Promise<void> {
  const hasManagedMappings = projectEndpoints(project).some(
    (endpoint) => endpoint.compose_service && endpoint.container_port,
  );
  const override = path.join(pathsFor(home).overrides, `${project.id}.yml`);
  assertInside(pathsFor(home).overrides, override, "Compose override");
  if (!hasManagedMappings) {
    await fs.rm(override, { force: true });
    delete project.compose_override;
    return;
  }
  await writeAtomic(override, composeOverrideYaml(project));
  project.compose_override = override;
}

async function addProjectUnlocked(
  home: string,
  options: AddProjectOptions,
): Promise<ProjectConfig> {
  const projectPath = path.resolve(options.path);
  const stat = await fs.stat(projectPath).catch(() => null);
  if (!stat?.isDirectory()) {
    throw new UnlocalhostError(`Project path does not exist or is not a directory: ${projectPath}`);
  }
  const slug = validateSlug(options.slug);
  if (
    options.port !== undefined &&
    (!Number.isInteger(options.port) || options.port < 1 || options.port > 65535)
  ) {
    throw new UnlocalhostError("--port must be an integer from 1 to 65535");
  }
  if (options.host && options.host !== "127.0.0.1" && options.host !== "localhost") {
    throw new UnlocalhostError(
      "v1 upstream hosts must be 127.0.0.1 or localhost; expose containers on loopback",
    );
  }
  if ((options.service && !options.containerPort) || (!options.service && options.containerPort)) {
    throw new UnlocalhostError("--service and --container-port must be provided together");
  }
  if (options.service && !options.compose) {
    throw new UnlocalhostError("--service requires --compose");
  }
  if (options.compose && options.run) {
    throw new UnlocalhostError("--run cannot be combined with --compose");
  }
  if (options.composePortServices !== undefined && !options.compose) {
    throw new UnlocalhostError("composePortServices requires a Compose file");
  }
  if (options.compose && options.port === undefined && !options.service) {
    throw new UnlocalhostError(
      'With --compose, omit --port only when --service and --container-port let unlocalhost generate the host mapping',
    );
  }
  if (options.service) validateComposeService(options.service);

  const existing = await listProjects(home);
  const config = await loadGlobalConfig(home);
  const selectedPort = options.port ?? (await allocatePort(config, existing));
  if (
    existing.some(
      (project) =>
        project.id === slug ||
        projectEndpoints(project).some((endpoint) => endpoint.slug === slug),
    )
  ) {
    throw new UnlocalhostError(`Project or slug "${slug}" is already registered`);
  }
  const duplicateUpstream = existing
    .flatMap((project) =>
      projectEndpoints(project).map((endpoint) => ({ project, endpoint })),
    )
    .find(
      ({ endpoint }) =>
        endpoint.upstream.host === (options.host ?? "127.0.0.1") &&
        endpoint.upstream.port === selectedPort,
    );
  if (duplicateUpstream) {
    throw new UnlocalhostError(
      `Port ${selectedPort} is already used by project "${duplicateUpstream.project.id}" endpoint "${duplicateUpstream.endpoint.id}"`,
    );
  }

  let composeFile: string | undefined;
  if (options.compose) {
    const absoluteCompose = path.resolve(projectPath, options.compose);
    assertInside(projectPath, absoluteCompose, "Compose file");
    if (!(await exists(absoluteCompose))) {
      throw new UnlocalhostError(`Compose file does not exist: ${absoluteCompose}`);
    }
    composeFile = path.relative(projectPath, absoluteCompose) || path.basename(absoluteCompose);
  }

  const project: ProjectConfig = {
    id: slug,
    name: options.name || path.basename(projectPath),
    path: projectPath,
    slug,
    enabled: true,
    public_enabled: options.public ?? true,
    ...((options.dev || options.run || options.devServer) ? { dev_mode: true } : {}),
    ...(options.devServer ? { dev_server: options.devServer } : {}),
    endpoints: [],
    upstream: {
      mode: "host_port",
      host: options.host ?? "127.0.0.1",
      port: selectedPort,
    },
  };
  if (composeFile) project.compose_file = composeFile;
  if (options.composePortServices !== undefined) {
    project.compose_port_services = [
      ...new Set(options.composePortServices.map(validateComposeService)),
    ];
  }
  if (options.run) project.run_command = options.run;
  if (options.service && options.containerPort) {
    project.compose_service = options.service;
    project.container_port = options.containerPort;
  }

  if (options.service && options.containerPort) {
    await updateComposeOverride(home, project);
  }

  await writeAtomic(projectFile(home, project.id), serializeProject(project));
  return project;
}

export async function addProject(
  home: string,
  options: AddProjectOptions,
): Promise<ProjectConfig> {
  return await withRegistryLock(home, async () => await addProjectUnlocked(home, options));
}

async function saveProject(home: string, project: ProjectConfig): Promise<void> {
  await writeAtomic(projectFile(home, project.id), serializeProject(project));
}

async function addEndpointUnlocked(
  home: string,
  projectId: string,
  options: AddEndpointOptions,
): Promise<EndpointConfig> {
  const project = await getProject(home, projectId);
  const id = validateSlug(options.id);
  if (id === "web") {
    throw new UnlocalhostError('"web" is reserved for the primary endpoint');
  }
  if (
    options.port !== undefined &&
    (!Number.isInteger(options.port) || options.port < 1 || options.port > 65535)
  ) {
    throw new UnlocalhostError("--port must be an integer from 1 to 65535");
  }
  const host = options.host ?? "127.0.0.1";
  if (host !== "127.0.0.1" && host !== "localhost") {
    throw new UnlocalhostError(
      "v1 upstream hosts must be 127.0.0.1 or localhost",
    );
  }
  if ((options.service && !options.containerPort) || (!options.service && options.containerPort)) {
    throw new UnlocalhostError("--service and --container-port must be provided together");
  }
  if (options.service && !project.compose_file) {
    throw new UnlocalhostError("--service requires a project registered with --compose");
  }
  if (
    options.service &&
    project.compose_override &&
    !project.compose_service &&
    project.endpoints.every((endpoint) => !endpoint.compose_service)
  ) {
    throw new UnlocalhostError(
      "The existing Compose override predates managed endpoint mappings; re-register the project before adding an automatic mapping",
    );
  }
  if (options.service) validateComposeService(options.service);
  const slug = validateSlug(options.slug ?? `${project.slug}-${id}`);
  const projects = await listProjects(home);
  const config = await loadGlobalConfig(home);
  const selectedPort = options.port ?? (await allocatePort(config, projects));
  const allEndpoints = projects.flatMap((registered) =>
    projectEndpoints(registered).map((endpoint) => ({ project: registered, endpoint })),
  );
  if (projectEndpoints(project).some((endpoint) => endpoint.id === id)) {
    throw new UnlocalhostError(`Endpoint "${id}" already exists in project "${project.id}"`);
  }
  const slugOwner = allEndpoints.find(({ endpoint }) => endpoint.slug === slug);
  if (slugOwner) {
    throw new UnlocalhostError(
      `Slug "${slug}" is already used by project "${slugOwner.project.id}" endpoint "${slugOwner.endpoint.id}"`,
    );
  }
  const upstreamOwner = allEndpoints.find(
    ({ endpoint }) =>
      endpoint.upstream.host === host && endpoint.upstream.port === selectedPort,
  );
  if (upstreamOwner) {
    throw new UnlocalhostError(
      `Port ${selectedPort} is already used by project "${upstreamOwner.project.id}" endpoint "${upstreamOwner.endpoint.id}"`,
    );
  }
  const endpoint: EndpointConfig = {
    id,
    slug,
    ...((options.dev || options.run || options.devServer) ? { dev_mode: true } : {}),
    ...(options.devServer ? { dev_server: options.devServer } : {}),
    upstream: { mode: "host_port", host, port: selectedPort },
  };
  if (options.run) endpoint.run_command = options.run;
  if (options.service && options.containerPort) {
    endpoint.compose_service = options.service;
    endpoint.container_port = options.containerPort;
  }
  project.endpoints.push(endpoint);
  if (options.service) await updateComposeOverride(home, project);
  await saveProject(home, project);
  return endpoint;
}

export async function addEndpoint(
  home: string,
  projectId: string,
  options: AddEndpointOptions,
): Promise<EndpointConfig> {
  return await withRegistryLock(
    home,
    async () => await addEndpointUnlocked(home, projectId, options),
  );
}

export async function setComposePortServices(
  home: string,
  projectId: string,
  services: string[],
): Promise<ProjectConfig> {
  return await withRegistryLock(home, async () => {
    const project = await getProject(home, projectId);
    if (!project.compose_file) {
      throw new UnlocalhostError(`Project "${project.id}" is not Compose-managed`);
    }
    project.compose_port_services = [
      ...new Set(services.map(validateComposeService)),
    ];
    await updateComposeOverride(home, project);
    await saveProject(home, project);
    return project;
  });
}

export async function removeEndpoint(
  home: string,
  projectId: string,
  endpointId: string,
): Promise<EndpointConfig> {
  const project = await getProject(home, projectId);
  const id = validateSlug(endpointId);
  if (id === "web") {
    throw new UnlocalhostError(
      'The primary "web" endpoint cannot be removed; remove the project instead',
    );
  }
  const index = project.endpoints.findIndex((endpoint) => endpoint.id === id);
  if (index === -1) {
    throw new UnlocalhostError(`Endpoint "${id}" is not registered in project "${project.id}"`);
  }
  const resolved = getEndpoint(project, id)!;
  await stopEndpointRunner(home, project, resolved);
  const [removed] = project.endpoints.splice(index, 1);
  if (removed?.compose_service) await updateComposeOverride(home, project);
  await saveProject(home, project);
  return removed!;
}

export async function setEndpointCommand(
  home: string,
  projectId: string,
  endpointId: string,
  command: string[],
): Promise<void> {
  if (command.length === 0 || command.some((part) => part.length === 0)) {
    throw new UnlocalhostError("Run command cannot be empty");
  }
  const project = await getProject(home, projectId);
  if (project.compose_file && endpointId === "web") {
    throw new UnlocalhostError(
      `Project "${project.id}" uses Compose for its primary endpoint; save the command on a secondary endpoint`,
    );
  }
  const id = validateSlug(endpointId);
  if (id === "web") {
    project.run_command = command;
    project.dev_mode = true;
  } else {
    const endpoint = project.endpoints.find((candidate) => candidate.id === id);
    if (!endpoint) {
      throw new UnlocalhostError(`Endpoint "${id}" is not registered in project "${project.id}"`);
    }
    endpoint.run_command = command;
    endpoint.dev_mode = true;
  }
  await saveProject(home, project);
}

export async function setEndpointDevMode(
  home: string,
  projectId: string,
  endpointId: string,
  enabled: boolean,
): Promise<void> {
  const project = await getProject(home, projectId);
  const id = validateSlug(endpointId);
  if (id === "web") {
    project.dev_mode = enabled;
  } else {
    const endpoint = project.endpoints.find((candidate) => candidate.id === id);
    if (!endpoint) {
      throw new UnlocalhostError(`Endpoint "${id}" is not registered in project "${project.id}"`);
    }
    endpoint.dev_mode = enabled;
  }
  await saveProject(home, project);
}

export async function setEndpointDevServer(
  home: string,
  projectId: string,
  endpointId: string,
  kind: DevServerKind,
): Promise<void> {
  const project = await getProject(home, projectId);
  const id = validateSlug(endpointId);
  if (id === "web") {
    project.dev_server = kind;
    project.dev_mode = true;
  } else {
    const endpoint = project.endpoints.find((candidate) => candidate.id === id);
    if (!endpoint) {
      throw new UnlocalhostError(`Endpoint "${id}" is not registered in project "${project.id}"`);
    }
    endpoint.dev_server = kind;
    endpoint.dev_mode = true;
  }
  await saveProject(home, project);
}

export async function removeProject(home: string, id: string): Promise<ProjectConfig> {
  const project = await getProject(home, id);
  await stopProjectRunners(home, project);
  await fs.unlink(projectFile(home, id));
  if (project.compose_override) {
    assertInside(pathsFor(home).overrides, project.compose_override, "Compose override");
    await fs.rm(project.compose_override, { force: true });
  }
  return project;
}

export async function setProjectPublicEnabled(
  home: string,
  id: string,
  enabled: boolean,
): Promise<ProjectConfig> {
  return await withRegistryLock(home, async () => {
    const project = await getProject(home, id);
    project.public_enabled = enabled;
    await saveProject(home, project);
    return project;
  });
}
