import { spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { UnlocalhostError } from "./errors.js";
import { type ResolvedEndpoint, projectEndpoints } from "./endpoints.js";
import { ensureDir, exists, writeAtomic } from "./files.js";
import { pathsFor } from "./paths.js";
import { endpointLocalUrl, endpointPublicUrl, localUrl, publicUrl } from "./urls.js";
import type { EndpointStatus, GlobalConfig, ProjectConfig } from "./types.js";

interface RunnerMetadata {
  project_id: string;
  endpoint_id: string;
  pid: number;
  command: string[];
  port: number;
  canonical_url?: string;
  runtime_version?: number;
  started_at: string;
}

const RUNNER_RUNTIME_VERSION = 3;

function metadataFile(home: string, projectId: string, endpointId: string): string {
  return path.join(pathsFor(home).run, `${projectId}--${endpointId}.json`);
}

function logFiles(home: string, projectId: string, endpointId: string): {
  stdout: string;
  stderr: string;
} {
  const directory = path.join(pathsFor(home).logs, "projects", projectId);
  return {
    stdout: path.join(directory, `${endpointId}.out.log`),
    stderr: path.join(directory, `${endpointId}.err.log`),
  };
}

function processRunning(pid: number): boolean {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export function managedViteConfigSource(
  projectConfig: string,
): string {
  return `// Generated by unlocalhost outside the project repository.
import projectConfig from ${JSON.stringify(pathToFileURL(projectConfig).href)};

export default async (environment) => {
  const original = typeof projectConfig === "function"
    ? await projectConfig(environment)
    : projectConfig;
  const endpoint = new URL(process.env.UNLOCALHOST_URL);
  const existingHmr = original?.server?.hmr;
  return {
    ...(original ?? {}),
    server: {
      ...(original?.server ?? {}),
      origin: endpoint.origin,
      hmr: {
        ...(typeof existingHmr === "object" ? existingHmr : {}),
        protocol: endpoint.protocol === "https:" ? "wss" : "ws",
        host: endpoint.hostname,
        clientPort: Number(endpoint.port || (endpoint.protocol === "https:" ? 443 : 80)),
      },
    },
  };
};
`;
}

async function prepareManagedViteConfig(
  home: string,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): Promise<string | null> {
  if (endpoint.id !== "vite" || !(await exists(path.join(project.path, "artisan")))) {
    return null;
  }
  const projectConfig = (
    await Promise.all(
      ["vite.config.ts", "vite.config.js", "vite.config.mts", "vite.config.mjs", "vite.config.cts", "vite.config.cjs"]
        .map(async (filename) => {
          const file = path.join(project.path, filename);
          return await exists(file) ? file : null;
        }),
    )
  ).find((file): file is string => file !== null);
  if (!projectConfig) return null;
  const directory = path.join(pathsFor(home).run, "vite-configs");
  const file = path.join(directory, `${project.id}--${endpoint.id}.mjs`);
  const source = managedViteConfigSource(projectConfig);
  await ensureDir(directory);
  const current = await fs.readFile(file, "utf8").catch(() => null);
  if (current !== source) await writeAtomic(file, source);
  return file;
}

export async function syncLaravelViteHotFile(
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
  canonicalUrl: string,
  waitForCreation = false,
): Promise<boolean> {
  if (endpoint.id !== "vite" || !(await exists(path.join(project.path, "artisan")))) {
    return false;
  }
  const hotFile = path.join(project.path, "public", "hot");
  if (waitForCreation) {
    for (let attempt = 0; attempt < 20 && !(await exists(hotFile)); attempt += 1) {
      await new Promise((resolve) => setTimeout(resolve, 100));
    }
  }
  if (!(await exists(hotFile))) return false;
  const current = (await fs.readFile(hotFile, "utf8")).trim();
  if (current === canonicalUrl) return false;
  await writeAtomic(hotFile, `${canonicalUrl}\n`);
  return true;
}

export function resolveRunCommand(
  command: string[],
  values: { host: string; port: number; localUrl: string; publicUrl: string | null },
): string[] {
  const canonicalUrl = values.publicUrl ?? values.localUrl;
  const replacements: Record<string, string> = {
    "{host}": values.host,
    "{port}": String(values.port),
    "{local_url}": values.localUrl,
    "{public_url}": values.publicUrl ?? "",
    "{url}": canonicalUrl,
  };
  return command.map((part) =>
    Object.entries(replacements).reduce(
      (resolved, [token, value]) => resolved.replaceAll(token, value),
      part,
    ),
  );
}

export function runnerEnvironment(
  config: GlobalConfig,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): NodeJS.ProcessEnv {
  const multiplexedVite = !endpoint.primary && endpoint.id === "vite";
  const local = multiplexedVite
    ? localUrl(project, config)
    : endpointLocalUrl(endpoint, config);
  const remote = multiplexedVite
    ? publicUrl(project, config)
    : endpointPublicUrl(endpoint, config, project.public_enabled !== false);
  const canonical = remote ?? local;
  const websocket = new URL(canonical);
  websocket.protocol = websocket.protocol === "https:" ? "wss:" : "ws:";
  return {
    ...process.env,
    HOST: endpoint.upstream.host,
    PORT: String(endpoint.upstream.port),
    VITE_PORT: String(endpoint.upstream.port),
    UNLOCALHOST_PROJECT: project.id,
    UNLOCALHOST_ENDPOINT: endpoint.id,
    UNLOCALHOST_PORT: String(endpoint.upstream.port),
    UNLOCALHOST_LOCAL_URL: local,
    ...(remote ? { UNLOCALHOST_PUBLIC_URL: remote } : {}),
    UNLOCALHOST_URL: canonical,
    UNLOCALHOST_WS_URL: websocket.toString().replace(/\/$/, ""),
  };
}

async function readMetadata(
  home: string,
  projectId: string,
  endpointId: string,
): Promise<RunnerMetadata | null> {
  const file = metadataFile(home, projectId, endpointId);
  if (!(await exists(file))) return null;
  try {
    const parsed = JSON.parse(await fs.readFile(file, "utf8")) as RunnerMetadata;
    if (!Number.isInteger(parsed.pid) || parsed.pid < 1) return null;
    return parsed;
  } catch {
    return null;
  }
}

export async function endpointRunnerStatus(
  home: string,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): Promise<EndpointStatus["process"]> {
  const metadata = await readMetadata(home, project.id, endpoint.id);
  const logs = logFiles(home, project.id, endpoint.id);
  const running = metadata ? processRunning(metadata.pid) : false;
  if (metadata && !running) {
    await fs.rm(metadataFile(home, project.id, endpoint.id), { force: true });
  }
  return {
    configured: Boolean(endpoint.run_command),
    running,
    pid: running ? metadata!.pid : null,
    command: running ? metadata!.command : endpoint.run_command ?? null,
    stdout_log: endpoint.run_command ? logs.stdout : null,
    stderr_log: endpoint.run_command ? logs.stderr : null,
  };
}

async function startEndpoint(
  home: string,
  config: GlobalConfig,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): Promise<{ endpoint: string; pid: number; already_running: boolean }> {
  if (!endpoint.run_command) {
    throw new UnlocalhostError(
      `Endpoint "${project.id}/${endpoint.id}" has no run command; use "unlocalhost endpoint set-command ${project.id} ${endpoint.id} <command...>"`,
    );
  }
  let existing = await readMetadata(home, project.id, endpoint.id);
  const environment = runnerEnvironment(config, project, endpoint);
  const managedViteConfig = await prepareManagedViteConfig(home, project, endpoint);
  if (
    existing &&
    processRunning(existing.pid) &&
    existing.canonical_url === environment.UNLOCALHOST_URL &&
    existing.runtime_version === RUNNER_RUNTIME_VERSION
  ) {
    await syncLaravelViteHotFile(project, endpoint, environment.UNLOCALHOST_URL!);
    return { endpoint: endpoint.id, pid: existing.pid, already_running: true };
  }
  if (existing && processRunning(existing.pid)) {
    await stopEndpoint(home, project, endpoint);
    existing = null;
  }
  const resolvedCommand = resolveRunCommand(endpoint.run_command, {
    host: endpoint.upstream.host,
    port: endpoint.upstream.port,
    localUrl: environment.UNLOCALHOST_LOCAL_URL!,
    publicUrl: environment.UNLOCALHOST_PUBLIC_URL ?? null,
  });
  if (managedViteConfig) resolvedCommand.push("--config", managedViteConfig);
  const [command, ...args] = resolvedCommand;
  if (!command) throw new UnlocalhostError(`Endpoint "${project.id}/${endpoint.id}" has an empty command`);
  const logs = logFiles(home, project.id, endpoint.id);
  await Promise.all([
    ensureDir(pathsFor(home).run),
    ensureDir(path.dirname(logs.stdout)),
  ]);
  const [stdout, stderr] = await Promise.all([
    fs.open(logs.stdout, "a", 0o600),
    fs.open(logs.stderr, "a", 0o600),
  ]);
  let child;
  try {
    child = spawn(command, args, {
      cwd: project.path,
      detached: true,
      env: environment,
      stdio: ["ignore", stdout.fd, stderr.fd],
    });
    await new Promise<void>((resolve, reject) => {
      child!.once("spawn", resolve);
      child!.once("error", reject);
    });
  } catch (error) {
    throw new UnlocalhostError(
      `Cannot start "${endpoint.run_command.join(" ")}" for ${project.id}/${endpoint.id}: ${String(error)}`,
    );
  } finally {
    await Promise.all([stdout.close(), stderr.close()]);
  }
  child.unref();
  const metadata: RunnerMetadata = {
    project_id: project.id,
    endpoint_id: endpoint.id,
    pid: child.pid!,
    command: resolvedCommand,
    port: endpoint.upstream.port,
    canonical_url: environment.UNLOCALHOST_URL!,
    runtime_version: RUNNER_RUNTIME_VERSION,
    started_at: new Date().toISOString(),
  };
  await writeAtomic(
    metadataFile(home, project.id, endpoint.id),
    `${JSON.stringify(metadata, null, 2)}\n`,
  );
  await new Promise((resolve) => setTimeout(resolve, 100));
  if (!processRunning(child.pid!)) {
    await fs.rm(metadataFile(home, project.id, endpoint.id), { force: true });
    throw new UnlocalhostError(
      `Process for ${project.id}/${endpoint.id} exited immediately; inspect ${logs.stderr}`,
    );
  }
  if (endpoint.id === "vite" && await exists(path.join(project.path, "artisan"))) {
    for (let attempt = 0; attempt < 50; attempt += 1) {
      try {
        await fetch(`http://${endpoint.upstream.host}:${endpoint.upstream.port}`, {
          signal: AbortSignal.timeout(200),
        });
        break;
      } catch {
        await new Promise((resolve) => setTimeout(resolve, 100));
      }
    }
  }
  await syncLaravelViteHotFile(
    project,
    endpoint,
    environment.UNLOCALHOST_URL!,
    true,
  );
  return { endpoint: endpoint.id, pid: child.pid!, already_running: false };
}

export async function startProjectRunners(
  home: string,
  config: GlobalConfig,
  project: ProjectConfig,
): Promise<Array<{ endpoint: string; pid: number; already_running: boolean }>> {
  const configured = projectEndpoints(project).filter((endpoint) => endpoint.run_command);
  if (configured.length === 0) {
    throw new UnlocalhostError(
      `Project "${project.id}" has no run commands; set one or manage its processes externally`,
    );
  }
  return await Promise.all(
    configured.map(
      async (endpoint) => await startEndpoint(home, config, project, endpoint),
    ),
  );
}

async function waitForExit(pid: number, milliseconds: number): Promise<boolean> {
  const deadline = Date.now() + milliseconds;
  while (Date.now() < deadline) {
    if (!processRunning(pid)) return true;
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  return !processRunning(pid);
}

async function stopEndpoint(
  home: string,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): Promise<{ endpoint: string; stopped: boolean }> {
  const metadata = await readMetadata(home, project.id, endpoint.id);
  if (!metadata || !processRunning(metadata.pid)) {
    await fs.rm(metadataFile(home, project.id, endpoint.id), { force: true });
    return { endpoint: endpoint.id, stopped: false };
  }
  try {
    if (process.platform === "win32") {
      process.kill(metadata.pid, "SIGTERM");
    } else {
      process.kill(-metadata.pid, "SIGTERM");
    }
  } catch {
    process.kill(metadata.pid, "SIGTERM");
  }
  if (!(await waitForExit(metadata.pid, 3000))) {
    try {
      if (process.platform === "win32") process.kill(metadata.pid, "SIGKILL");
      else process.kill(-metadata.pid, "SIGKILL");
    } catch {
      process.kill(metadata.pid, "SIGKILL");
    }
    await waitForExit(metadata.pid, 1000);
  }
  await fs.rm(metadataFile(home, project.id, endpoint.id), { force: true });
  return { endpoint: endpoint.id, stopped: true };
}

export async function stopEndpointRunner(
  home: string,
  project: ProjectConfig,
  endpoint: ResolvedEndpoint,
): Promise<{ endpoint: string; stopped: boolean }> {
  return await stopEndpoint(home, project, endpoint);
}

export async function stopProjectRunners(
  home: string,
  project: ProjectConfig,
): Promise<Array<{ endpoint: string; stopped: boolean }>> {
  return await Promise.all(
    projectEndpoints(project).map(
      async (endpoint) => await stopEndpoint(home, project, endpoint),
    ),
  );
}

export async function readEndpointLogs(
  home: string,
  projectId: string,
  endpointId: string,
  stream: "stdout" | "stderr",
  lines: number,
): Promise<string> {
  const file = logFiles(home, projectId, endpointId)[stream];
  if (!(await exists(file))) {
    throw new UnlocalhostError(`No ${stream} log exists for ${projectId}/${endpointId}`);
  }
  const content = await fs.readFile(file, "utf8");
  return content.split(/\r?\n/).slice(-lines - 1).join("\n").replace(/^\n/, "");
}
