import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import crypto from "node:crypto";
import { dependencyHelp } from "./dependencies.js";
import { projectEndpoints } from "./endpoints.js";
import { UnlocalhostError } from "./errors.js";
import { exists, writeAtomic } from "./files.js";
import { pathsFor } from "./paths.js";
import { commandExists, runCommand } from "./process.js";
import type { GlobalConfig, ProjectConfig } from "./types.js";
import { publicHostnameForSlug } from "./urls.js";

export interface TunnelRecord {
  id: string;
  name: string;
}

export interface DnsRouteResult {
  hostname: string;
  status: "created" | "updated" | "unchanged";
}

export function generateCloudflaredConfig(
  home: string,
  config: GlobalConfig,
  tunnelId: string,
): string {
  const credentials = path.join(pathsFor(home).cloudflared, `${tunnelId}.json`);
  return `# Generated by unlocalhost. Exact project DNS records select this machine.
tunnel: ${tunnelId}
credentials-file: ${JSON.stringify(credentials)}

ingress:
  - service: http://127.0.0.1:${config.caddy_http_port}
`;
}

export function projectPublicHostnames(
  config: GlobalConfig,
  projects: ProjectConfig[],
): string[] {
  if (!config.public_domain) return [];
  return [...new Set(
    projects
      .filter((project) => project.enabled && project.public_enabled !== false)
      .flatMap((project) =>
        projectEndpoints(project)
          .filter((endpoint) => endpoint.primary || endpoint.id !== "vite")
          .map((endpoint) => publicHostnameForSlug(endpoint.slug, config)),
      )
      .filter((hostname): hostname is string => Boolean(hostname)),
  )].sort();
}

export async function listTunnels(): Promise<TunnelRecord[]> {
  if (!commandExists("cloudflared")) {
    throw new UnlocalhostError(dependencyHelp("cloudflared"));
  }
  const result = await runCommand("cloudflared", ["tunnel", "list", "--output", "json"]);
  if (result.code !== 0) {
    throw new UnlocalhostError(
      `Cannot list Cloudflare tunnels: ${result.stderr || result.stdout}. Run "cloudflared tunnel login" first.`,
    );
  }
  try {
    const parsed = JSON.parse(result.stdout) as Array<Record<string, unknown>>;
    return parsed
      .filter((item) => typeof item.id === "string" && typeof item.name === "string")
      .map((item) => ({ id: String(item.id), name: String(item.name) }));
  } catch {
    throw new UnlocalhostError("cloudflared returned invalid JSON while listing tunnels");
  }
}

async function findCredentials(home: string, tunnelId: string): Promise<string> {
  const destination = path.join(pathsFor(home).cloudflared, `${tunnelId}.json`);
  if (await exists(destination)) return destination;
  const candidates = [
    path.join(os.homedir(), ".cloudflared", `${tunnelId}.json`),
    path.join(os.homedir(), ".cloudflare-warp", `${tunnelId}.json`),
  ];
  const source = (await Promise.all(candidates.map(async (file) => ((await exists(file)) ? file : null))))
    .find((file): file is string => file !== null);
  if (!source) {
    throw new UnlocalhostError(
      `Tunnel ${tunnelId} exists, but its credentials file was not found; recreate it or copy it to ${destination}`,
    );
  }
  await fs.copyFile(source, destination);
  await fs.chmod(destination, 0o600);
  return destination;
}

async function createTunnel(name: string): Promise<TunnelRecord> {
  const result = await runCommand("cloudflared", ["tunnel", "create", name]);
  if (result.code !== 0) {
    throw new UnlocalhostError(
      `Cannot create tunnel "${name}": ${result.stderr || result.stdout}. Run "cloudflared tunnel login" first.`,
    );
  }
  const tunnels = await listTunnels();
  const tunnel = tunnels.find((item) => item.name === name);
  if (!tunnel) throw new UnlocalhostError(`Tunnel "${name}" was created but could not be found`);
  return tunnel;
}

async function tokenFromEnvironment(): Promise<string | null> {
  if (process.env.CLOUDFLARE_API_TOKEN) return process.env.CLOUDFLARE_API_TOKEN;
  if (process.env.CLOUDFLARE_API_TOKEN_FILE) {
    return (await fs.readFile(process.env.CLOUDFLARE_API_TOKEN_FILE, "utf8")).trim();
  }
  return null;
}

async function cloudflareRequest(
  token: string,
  method: string,
  endpoint: string,
  body?: unknown,
): Promise<Record<string, unknown>> {
  const response = await fetch(`https://api.cloudflare.com/client/v4${endpoint}`, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    ...(body === undefined ? {} : { body: JSON.stringify(body) }),
  });
  const data = (await response.json()) as Record<string, unknown>;
  if (!response.ok || data.success !== true) {
    throw new UnlocalhostError(`Cloudflare API request failed (${response.status}): ${JSON.stringify(data.errors ?? data)}`);
  }
  return data;
}

async function listTunnelsWithApi(
  token: string,
  accountId: string,
  name: string,
): Promise<TunnelRecord[]> {
  const query = new URLSearchParams({ is_deleted: "false", name });
  const response = await cloudflareRequest(
    token,
    "GET",
    `/accounts/${encodeURIComponent(accountId)}/cfd_tunnel?${query.toString()}`,
  );
  const records = Array.isArray(response.result)
    ? (response.result as Array<Record<string, unknown>>)
    : [];
  return records
    .filter((item) => typeof item.id === "string" && typeof item.name === "string")
    .map((item) => ({ id: String(item.id), name: String(item.name) }));
}

async function createTunnelWithApi(
  home: string,
  token: string,
  accountId: string,
  name: string,
): Promise<TunnelRecord> {
  const tunnelSecret = crypto.randomBytes(32).toString("base64");
  const response = await cloudflareRequest(
    token,
    "POST",
    `/accounts/${encodeURIComponent(accountId)}/cfd_tunnel`,
    {
      name,
      config_src: "local",
      tunnel_secret: tunnelSecret,
    },
  );
  const result = response.result as Record<string, unknown> | undefined;
  if (!result || typeof result.id !== "string") {
    throw new UnlocalhostError("Cloudflare created the tunnel but returned no tunnel id");
  }
  const tunnel = { id: result.id, name };
  await writeAtomic(
    path.join(pathsFor(home).cloudflared, `${tunnel.id}.json`),
    `${JSON.stringify(
      {
        AccountTag: accountId,
        TunnelSecret: tunnelSecret,
        TunnelID: tunnel.id,
      },
      null,
      2,
    )}\n`,
  );
  return tunnel;
}

async function ensureDnsWithApi(
  token: string,
  zoneId: string,
  hostname: string,
  tunnelId: string,
): Promise<"created" | "updated" | "unchanged"> {
  const name = hostname;
  const content = `${tunnelId}.cfargotunnel.com`;
  const query = new URLSearchParams({ type: "CNAME", name });
  const listed = await cloudflareRequest(
    token,
    "GET",
    `/zones/${encodeURIComponent(zoneId)}/dns_records?${query.toString()}`,
  );
  const records = Array.isArray(listed.result)
    ? (listed.result as Array<Record<string, unknown>>)
    : [];
  const record = records[0];
  const desired = { type: "CNAME", name, content, proxied: true, ttl: 1 };
  if (!record) {
    await cloudflareRequest(
      token,
      "POST",
      `/zones/${encodeURIComponent(zoneId)}/dns_records`,
      desired,
    );
    return "created";
  }
  if (record.content === content && record.proxied === true) return "unchanged";
  await cloudflareRequest(
    token,
    "PUT",
    `/zones/${encodeURIComponent(zoneId)}/dns_records/${encodeURIComponent(String(record.id))}`,
    desired,
  );
  return "updated";
}

async function ensureDnsWithCloudflared(
  tunnelId: string,
  hostname: string,
): Promise<"created"> {
  const result = await runCommand("cloudflared", [
    "tunnel",
    "route",
    "dns",
    "--overwrite-dns",
    tunnelId,
    hostname,
  ]);
  if (result.code !== 0) {
    throw new UnlocalhostError(
      `DNS for ${hostname} was not configured: ${result.stderr || result.stdout}. Set CLOUDFLARE_API_TOKEN and cloudflare_zone_id, or authenticate with "cloudflared tunnel login".`,
    );
  }
  return "created";
}

export async function ensureDnsRoutes(
  config: GlobalConfig,
  tunnelId: string,
  hostnames: string[],
): Promise<DnsRouteResult[]> {
  const token = await tokenFromEnvironment();
  const unique = [...new Set(hostnames)].sort();
  const results: DnsRouteResult[] = [];
  for (const hostname of unique) {
    const status =
      token && config.cloudflare_zone_id
        ? await ensureDnsWithApi(
            token,
            config.cloudflare_zone_id,
            hostname,
            tunnelId,
          )
        : await ensureDnsWithCloudflared(tunnelId, hostname);
    results.push({ hostname, status });
  }
  return results;
}

export async function initializeTunnel(
  home: string,
  config: GlobalConfig,
  hostnames: string[] = [],
): Promise<{ tunnel: TunnelRecord; dns: DnsRouteResult[]; configFile: string }> {
  if (!config.public_domain) {
    throw new UnlocalhostError(
      'Set public_domain in config.toml or pass "--domain" to "unlocalhost tunnel init"',
    );
  }
  const token = await tokenFromEnvironment();
  const useApi = Boolean(token && config.cloudflare_account_id);
  const tunnels = useApi
    ? await listTunnelsWithApi(token!, config.cloudflare_account_id, config.tunnel_name)
    : await listTunnels();
  const duplicates = tunnels.filter((item) => item.name === config.tunnel_name);
  if (duplicates.length > 1) {
    throw new UnlocalhostError(
      `More than one tunnel is named "${config.tunnel_name}"; remove duplicates before continuing`,
    );
  }
  const tunnel =
    duplicates[0] ??
    (useApi
      ? await createTunnelWithApi(
          home,
          token!,
          config.cloudflare_account_id,
          config.tunnel_name,
        )
      : await createTunnel(config.tunnel_name));
  await findCredentials(home, tunnel.id);
  const configFile = pathsFor(home).cloudflaredConfig;
  await writeAtomic(configFile, generateCloudflaredConfig(home, config, tunnel.id));
  const dns = await ensureDnsRoutes(config, tunnel.id, hostnames);
  return { tunnel, dns, configFile };
}

export async function readTunnelId(home: string): Promise<string> {
  const file = pathsFor(home).cloudflaredConfig;
  if (!(await exists(file))) throw new UnlocalhostError('Tunnel is not initialized; run "unlocalhost tunnel init"');
  const source = await fs.readFile(file, "utf8");
  const match = /^tunnel:\s*([0-9a-f-]+)\s*$/im.exec(source);
  if (!match?.[1]) throw new UnlocalhostError(`Cannot read tunnel id from ${file}`);
  return match[1];
}
